/// <reference lib="deno.ns" />
/**
 * scripts/bump.ts
 *
 * Called automatically by .githooks/post-commit after every git commit.
 *
 * What it does:
 *   1. Reads the last commit message
 *   2. Bumps patch version (or minor if commit starts with "feat:")
 *   3. Detects any newly drawn birds from the diff of birds.json
 *   4. Appends an entry to CHANGELOG.md
 *   5. Stages version.json + CHANGELOG.md and amends the commit silently
 */

import { VersionManager } from './versionManager.ts';

// ---------------------------------------------------------------------------
// Git helpers
// ---------------------------------------------------------------------------

async function git(...args: string[]): Promise<string> {
  const cmd = new Deno.Command('git', { args, stdout: 'piped', stderr: 'piped' });
  const { code, stdout, stderr } = await cmd.output();
  if (code !== 0) {
    throw new Error(`git ${args.join(' ')} failed:\n${new TextDecoder().decode(stderr)}`);
  }
  return new TextDecoder().decode(stdout).trim();
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  // 1. Get the commit message that was just made
  const commitMsg = await git('log', '-1', '--pretty=%s');

  // Skip if this commit was itself generated by this script (avoid infinite loop)
  if (commitMsg === '__version_bump__') {
    console.log('[bump] Skipping version-bump commit.');
    return;
  }

  console.log(`[bump] Commit: "${commitMsg}"`);

  // 2. Detect newly drawn birds BEFORE bumping (diff is HEAD~1 vs HEAD)
  const newDrawings = await VersionManager.getNewlyDrawnFromDiff();
  if (newDrawings.length > 0) {
    console.log(`[bump] New drawings detected: ${newDrawings.map((d) => d.name).join(', ')}`);
  }

  // 3. Bump version
  const version = await VersionManager.bumpAuto(commitMsg);
  console.log(`[bump] Version → ${VersionManager.format(version)}`);

  // 4. Append to changelog
  await VersionManager.appendChangelog(version, commitMsg, newDrawings);
  console.log('[bump] Changelog updated.');

  // 5. Stage the changed files and amend the commit silently
  //    Using --no-verify so the hook doesn't fire again
  //    The amended commit message is kept identical to the original
  try {
    const { FILES } = await import('./utils.ts');
    await git('add', FILES.version, FILES.changelog);
    await git(
      'commit',
      '--amend',
      '--no-edit', // keep original commit message
      '--no-verify', // skip hooks on the amend
      '--quiet',
    );
    console.log('[bump] Commit amended with version + changelog.');
  } catch (e) {
    // Non-fatal: if amend fails (e.g. nothing staged) just warn
    console.warn('[bump] Could not amend commit:', (e as Error).message);
  }
}

main().catch((e) => {
  console.error('[bump] Error:', e);
  Deno.exit(1);
});
