/// <reference lib="deno.ns" />

// === CONFIGURATION ===
const HUMAN_VERSION = '0.5.0';
const FILES = {
  data: './public/birds.json',
  json: './src/version.json',
  ts: './src/version.ts',
};
// =====================

// Define structure to avoid 'any' errors
interface Bird {
  drawn?: string;
  [key: string]: unknown;
}

export async function updateVersion() {
  console.log('🦜 Counting drawn birds...');

  let birdCount = 0;
  try {
    const text = await Deno.readTextFile(FILES.data);
    const data = JSON.parse(text);

    // Helper: Counts items that actually have a 'drawn' property
    const countDrawn = (list: unknown[]): number => {
      return list.filter((item) => {
        const b = item as Bird;
        // Check if 'drawn' exists and is a valid string
        return b.drawn && typeof b.drawn === 'string' && b.drawn.length > 0;
      }).length;
    };

    if (Array.isArray(data)) {
      // Flat Array
      birdCount = countDrawn(data);
    } else if (typeof data === 'object' && data !== null) {
      // Grouped Object (Families)
      for (const key of Object.keys(data)) {
        const group = (data as Record<string, unknown>)[key];
        if (Array.isArray(group)) {
          birdCount += countDrawn(group);
        }
      }
    }
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(`❌ Error reading bird data: ${msg}`);
    Deno.exit(1);
  }

  const fullVersion = `${HUMAN_VERSION}+${birdCount}`;
  console.log(`✅ Counted ${birdCount} drawn birds. Version: ${fullVersion}`);

  // 1. Write to JSON (Easy to read for other tools)
  const jsonContent = {
    human: HUMAN_VERSION,
    count: birdCount,
    full: fullVersion,
    updated: new Date().toISOString(),
  };
  await Deno.writeTextFile(FILES.json, JSON.stringify(jsonContent, null, 2));

  // 2. Write to TS (For app import)
  const tsContent = `// Auto-generated by script/update_version.ts
export const APP_VERSION = "${fullVersion}";
export const BIRD_COUNT = ${birdCount};
`;
  await Deno.writeTextFile(FILES.ts, tsContent);

  return fullVersion;
}

if (import.meta.main) {
  await updateVersion();
}
