/// <reference lib="deno.ns" />

// === CONFIGURATION ===
const HUMAN_VERSION = '0.6.0';

const FILES = {
  data: './public/birds.json', // Source JSON
  thumb: './public/thumb', // Thumbnail Folder
  full: './public/full', // Full Image Folder
  json: './src/version.json', // Output JSON
  ts: './src/version.ts', // Output TS
};
// =====================

interface Bird {
  drawn?: string;
  [key: string]: unknown;
}

/**
 * Helper to count .webp files in a directory
 */
async function countWebpFiles(dirPath: string): Promise<number> {
  let count = 0;
  try {
    for await (const entry of Deno.readDir(dirPath)) {
      if (entry.isFile && entry.name.endsWith('.webp') && entry.name !== 'placeholder.webp') {
        count++;
      }
    }
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      console.warn(`⚠️ Directory not found: ${dirPath}`);
      return 0;
    }
    throw error;
  }
  return count;
}

export async function updateVersion() {
  console.log('🔍 Starting Integrity Check...');

  // 1. Count JSON "Drawn" Birds
  let jsonCount = 0;
  try {
    const text = await Deno.readTextFile(FILES.data);
    const data = JSON.parse(text);

    const countDrawn = (list: unknown[]) =>
      list.filter((item) => {
        const b = item as Bird;
        return b.drawn && typeof b.drawn === 'string' && b.drawn.length > 0;
      }).length;

    if (Array.isArray(data)) {
      jsonCount = countDrawn(data);
    } else {
      for (const key of Object.keys(data)) {
        const group = (data as Record<string, unknown>)[key];
        if (Array.isArray(group)) jsonCount += countDrawn(group);
      }
    }
  } catch (e) {
    console.error(`❌ Error reading JSON: ${e}`);
    Deno.exit(1);
  }

  // 2. Count Files in Directories
  const thumbCount = await countWebpFiles(FILES.thumb);
  const fullCount = await countWebpFiles(FILES.full);

  console.log(`📊 Stats:
  - JSON Drawn Entries: ${jsonCount}
  - Thumbnail Files:    ${thumbCount}
  - Full Size Files:    ${fullCount}
  `);

  // 3. The Robust Check (Triple Tally)
  if (jsonCount !== thumbCount || jsonCount !== fullCount) {
    console.error('❌ INTEGRITY CHECK FAILED: Counts do not match!');

    if (jsonCount !== thumbCount) {
      console.error(`   👉 JSON says ${jsonCount}, but found ${thumbCount} thumbnails.`);
    }
    if (jsonCount !== fullCount) {
      console.error(`   👉 JSON says ${jsonCount}, but found ${fullCount} full images.`);
    }
    if (thumbCount !== fullCount) {
      console.error(`   👉 Image folders mismatch (Thumb: ${thumbCount} vs Full: ${fullCount}).`);
    }

    Deno.exit(1); // Stop the ship!
  }

  console.log('✅ Integrity Check Passed. All counts tally.');

  // 4. Update Version Files
  const fullVersion = `${HUMAN_VERSION}+${jsonCount}`;

  const jsonContent = {
    human: HUMAN_VERSION,
    count: jsonCount,
    full: fullVersion,
    updated: new Date().toISOString(),
  };
  await Deno.writeTextFile(FILES.json, JSON.stringify(jsonContent, null, 2));

  const tsContent = `// Auto-generated by script/update_version.ts
export const APP_VERSION = "${fullVersion}";
export const BIRD_COUNT = ${jsonCount};
`;
  await Deno.writeTextFile(FILES.ts, tsContent);

  return fullVersion;
}

if (import.meta.main) {
  await updateVersion();
}
